### ISSUE TITLE
support RDV40?

### ISSUE THREAD

**Issue by K7-Lenovo** [AndProx/AndProx#31] opened 2018-11-01 03:15 UTC
i flash my pm3 rdv40 to [this](https://github.com/proxmark/proxmark3/tree/bed3db8f1dea15b9e998c3c4c432c58c5eb565eb) firmware version but it still pop up a window told me my firmware is incorrect

**Comment by micolous** [comment] 2018-11-04 06:38
What does the output of `hw version` say when it is connected to your PC?

**Comment by micolous** [comment] 2018-11-09 14:21
The fact that it doesn't work with iceman's version or the official version on your PC sounds a lot like your device has other issues. This could be caused by a bad firmware flash.

If you can't get `hw version` going, I'll need some other information to see if you can get out of this state:

1. What does `dmesg` on your PC say when you plug it in?
2. What does `dmesg` say when holding down the PM3-button when plugging it in? (note: this forces it to enter bootloader mode)

If you get _something_ that looks like a serial interface (in either of those), then it should be possible to recover using USB alone. Otherwise, you'll need to [reflash it using a JTAG interface](https://github.com/proxmark/proxmark3/wiki/Debricking-Proxmark3-with-buspirate).

Your next step would be to get the current upstream firmware, and using a totally clean build of the software -- that is, clone the code into a complete new directory, and build the flasher and firmware there.  You should not flash the bootloader, and should be able to just flash fullimage.elf.

You should be able to get away with flashing the official mainline 3.1.0 firmware on your PM3 and using AndProx with that, even when using the version on the Play Store, at least for the basics.  There are a couple of reasons I suggested a specific version:

1. It matches what the Play Store version of AndProx uses.
2. There are a number of Android devices with compatibility issues caused by PM3's USB descriptors, which is fixed in a newer version.
3. Other forks use slightly different command codes, which can cause unexpected behaviour.

The actual check looks to see if you have some third-party firmware on there, or if your version is too old.  It doesn't check if your firmware is newer.

**Comment by K7-Lenovo** [comment] 2018-11-13 13:59
> The fact that it doesn't work with iceman's version or the official version on your PC sounds a lot like your device has other issues. This could be caused by a bad firmware flash.
> 
> If you can't get `hw version` going, I'll need some other information to see if you can get out of this state:
> 
> 1. What does `dmesg` on your PC say when you plug it in?
> 2. What does `dmesg` say when holding down the PM3-button when plugging it in? (note: this forces it to enter bootloader mode)
> 
> If you get _something_ that looks like a serial interface (in either of those), then it should be possible to recover using USB alone. Otherwise, you'll need to [reflash it using a JTAG interface](https://github.com/proxmark/proxmark3/wiki/Debricking-Proxmark3-with-buspirate).
> 
> Your next step would be to get the current upstream firmware, and using a totally clean build of the software -- that is, clone the code into a complete new directory, and build the flasher and firmware there. You should not flash the bootloader, and should be able to just flash fullimage.elf.
> 
> You should be able to get away with flashing the official mainline 3.1.0 firmware on your PM3 and using AndProx with that, even when using the version on the Play Store, at least for the basics. There are a couple of reasons I suggested a specific version:
> 
> 1. It matches what the Play Store version of AndProx uses.
> 2. There are a number of Android devices with compatibility issues caused by PM3's USB descriptors, which is fixed in a newer version.
> 3. Other forks use slightly different command codes, which can cause unexpected behaviour.
> 
> The actual check looks to see if you have some third-party firmware on there, or if your version is too old. It doesn't check if your firmware is newer.

 [ CLIENT ]
 client: iceman build for RDV40 with flashmem; smartcard;

 [ ARM ]
 bootrom: iceman// 2018-11-07 23:58:08
      os: iceman// 2018-11-07 23:58:57

 [ FPGA ]
 LF image built for 2s30vq100 on 2018/ 9/ 8 at 13:57:51
 HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23

**Comment by K7-Lenovo** [comment] 2018-11-13 14:01
> The fact that it doesn't work with iceman's version or the official version on your PC sounds a lot like your device has other issues. This could be caused by a bad firmware flash.
> 
> If you can't get `hw version` going, I'll need some other information to see if you can get out of this state:
> 
> 1. What does `dmesg` on your PC say when you plug it in?
> 2. What does `dmesg` say when holding down the PM3-button when plugging it in? (note: this forces it to enter bootloader mode)
> 
> If you get _something_ that looks like a serial interface (in either of those), then it should be possible to recover using USB alone. Otherwise, you'll need to [reflash it using a JTAG interface](https://github.com/proxmark/proxmark3/wiki/Debricking-Proxmark3-with-buspirate).
> 
> Your next step would be to get the current upstream firmware, and using a totally clean build of the software -- that is, clone the code into a complete new directory, and build the flasher and firmware there. You should not flash the bootloader, and should be able to just flash fullimage.elf.
> 
> You should be able to get away with flashing the official mainline 3.1.0 firmware on your PM3 and using AndProx with that, even when using the version on the Play Store, at least for the basics. There are a couple of reasons I suggested a specific version:
> 
> 1. It matches what the Play Store version of AndProx uses.
> 2. There are a number of Android devices with compatibility issues caused by PM3's USB descriptors, which is fixed in a newer version.
> 3. Other forks use slightly different command codes, which can cause unexpected behaviour.
> 
> The actual check looks to see if you have some third-party firmware on there, or if your version is too old. It doesn't check if your firmware is newer.

how should i get `dmesg` say? i got no `dmesg` command by send it in client/proxmark3.exe

**Comment by micolous** [comment] 2018-11-24 22:34
`dmesg` is a Linux command that shows the kernel log, so that won't help you on Windows.  Windows doesn't show similar information in an easy to access way.  But that's OK, the fact that [you managed to get some output suggests that you've got it living again anyway](https://github.com/AndProx/AndProx/issues/31#issuecomment-438275083).

Looking at the version output, you definitely still have the iceman firmware on there.

I found that there was a bug in AndProx's version detection logic which would block you from running if you had iceman's _bootloader_ on your PM3.  Because the bootloader version doesn't really matter, and I don't want people to needlessly reflash their bootloader, [I have now removed that restriction](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae).

This [fix](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae) will come in the next AndProx release (which will be based on the 3.1.0 client).

**Comment by K7-Lenovo** [comment] 2018-11-25 19:52
> `dmesg` is a Linux command that shows the kernel log, so that won't help you on Windows. Windows doesn't show similar information in an easy to access way. But that's OK, the fact that [you managed to get some output suggests that you've got it living again anyway](https://github.com/AndProx/AndProx/issues/31#issuecomment-438275083).
> 
> Looking at the version output, you definitely still have the iceman firmware on there.
> 
> I found that there was a bug in AndProx's version detection logic which would block you from running if you had iceman's _bootloader_ on your PM3. Because the bootloader version doesn't really matter, and I don't want people to needlessly reflash their bootloader, [I have now removed that restriction](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae).
> 
> This [fix](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae) will come in the next AndProx release (which will be based on the 3.1.0 client).

`pm3 ~$ client/proxmark3.exe com3
Prox/RFID mark3 RFID instrument
bootrom: /-suspect 2018-11-25 19:14:51
os: /-suspect 2018-11-25 19:15:24
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2018/08/13 at 21:22:51`
it still went wrong with this firmware

**Comment by K7-Lenovo** [comment] 2018-11-25 19:53
> `dmesg` is a Linux command that shows the kernel log, so that won't help you on Windows. Windows doesn't show similar information in an easy to access way. But that's OK, the fact that [you managed to get some output suggests that you've got it living again anyway](https://github.com/AndProx/AndProx/issues/31#issuecomment-438275083).
> 
> Looking at the version output, you definitely still have the iceman firmware on there.
> 
> I found that there was a bug in AndProx's version detection logic which would block you from running if you had iceman's _bootloader_ on your PM3. Because the bootloader version doesn't really matter, and I don't want people to needlessly reflash their bootloader, [I have now removed that restriction](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae).
> 
> This [fix](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae) will come in the next AndProx release (which will be based on the 3.1.0 client).

[https://github.com/proxmark/proxmark3/tree/bed3db8f1dea15b9e998c3c4c432c58c5eb565eb](make by this)

**Comment by K7-Lenovo** [comment] 2018-11-28 19:48
> `dmesg` is a Linux command that shows the kernel log, so that won't help you on Windows. Windows doesn't show similar information in an easy to access way. But that's OK, the fact that [you managed to get some output suggests that you've got it living again anyway](https://github.com/AndProx/AndProx/issues/31#issuecomment-438275083).
> 
> Looking at the version output, you definitely still have the iceman firmware on there.
> 
> I found that there was a bug in AndProx's version detection logic which would block you from running if you had iceman's _bootloader_ on your PM3. Because the bootloader version doesn't really matter, and I don't want people to needlessly reflash their bootloader, [I have now removed that restriction](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae).
> 
> This [fix](https://github.com/AndProx/AndProx/commit/35b3090d4258be556f8a70b507bd118872c14dae) will come in the next AndProx release (which will be based on the 3.1.0 client).

`Prox/RFID mark3 RFID instrument
bootrom: /-suspect 2018-11-03 06:58:45
os: remove-le32toh/v3.0.1-400-gbed3db8f-suspect 2018-09-09 13:30:16
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2018/08/13 at 21:22:51
uC: AT91SAM7S512 Rev B
Embedded Processor: ARM7TDMI
Nonvolatile Program Memory Size: 512K bytes. Used: 193851 bytes (37%). Free: 330437 bytes (63%).
Second Nonvolatile Program Memory Size: None
Internal SRAM Size: 64K bytes
Architecture Identifier: AT91SAM7Sxx Series
Nonvolatile Program Memory Type: Embedded Flash Memory`
i flash it by jlink and this version don't work too.

**Comment by K7-Lenovo** [comment] 2018-12-13 06:59
'Prox/RFID mark3 RFID instrument
bootrom: /-suspect 2018-12-13 06:35:33
os: HEAD/v3.1.0-suspect 2018-12-01 08:57:42
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2018/09/12 at 15:18:46
SmartCard Slot: available'

still can not connect in 2.0.4

**Comment by micolous** [comment] 2018-12-28 06:05
I have fixed the original issue that you were having, and that's in AndProx 2.0.4 (Iceman bootloader with Mainline firmware). I'm marking this as closed because your original issue was fixed.

The issues you have had since then are _different_ -- you _now_ have a broken build of the bootloader that doesn't have correct version information (`bootrom: /-suspect`).  I have no idea what version of the bootloader you actually have.

This is also present on a number of devices shipped from (primarily) Chinese sellers who do not release source code to their modifications, and [like the rest of the PM3 community](http://www.proxmark.org/forum/viewtopic.php?id=5515), _I intentionally do not wish to support these at all_.

This version information is populated from `git`. If you downloaded a ZIP file from GitHub, the `.git` directories are missing, or `git` is not installed, then this doesn't work. (see: https://github.com/Proxmark/proxmark3/issues/12)

There are two ways to resolve your issue:

1. Get the original RDV4.0 _bootloader_ image and then flash that to your device.

2. Get a working PM3 build environment running, and then [flash your device with that](https://github.com/Proxmark/proxmark3/wiki/flashing#flashing-procedure).

If you're stuck, [start with the Getting Started guide](https://github.com/Proxmark/proxmark3/wiki/Getting-Started).

**Closed by micolous** 2018-12-28 06:05 UTC
