### ISSUE TITLE
FEATURE REQUEST: Support for other builds.

### ISSUE THREAD

**Issue by slycooper724** [AndProx/AndProx#52] opened 2021-07-16 14:07 UTC
## Is your feature request related to a problem? Please describe.
Not being able to use different builds of the Proxmark3 firmware with the app is very limiting.

## Describe the solution you'd like
I'd like to see more support for different builds of the Proxmark3 firmware. This is as simple as compiling a different build, which I can do in Termux, but Termux doesn't work on all devices due to rooting being required.

## Describe alternatives you've considered
Use a different app, or use an actual computer.

## Additional context
Regards complete.

**Comment by micolous** [comment] 2021-07-18 00:44
Each fork needs its own build of AndProx, and those forks need to have a way to hijack device communications.

Duplicate of #12.

**Closed by micolous** 2021-07-18 00:44 UTC
